name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install cmake make 
      run: sudo apt install cmake
    - name: CatLog
      run: cd CatLog
    - name: ls
      run: ls 


